/**
 * TypeScript row types for every database table.
 *
 * All fields are camelCase. wrapIdentifier and postProcessResponse in
 * src/db/index.ts handle the conversion between camelCase (JS) and
 * snake_case (PostgreSQL) automatically at the Knex layer.
 *
 * Convention:
 *   - XxxRow       — the full shape of a row as returned by SELECT
 *   - XxxInsert    — Omit<XxxRow, DB-generated fields> used for INSERT
 *
 * DB-generated fields omitted from Insert types:
 *   - id           — generated by application code (uuidv7()) before insert,
 *                    so it IS included in Insert types
 *   - createdAt    — defaultTo(knex.fn.now()) in migration
 *   - updatedAt    — defaultTo(knex.fn.now()) in migration
 *
 * Note: 'id' is included in Insert types because we generate it with
 * uuidv7() in the application before calling insert(), rather than
 * relying on a database sequence or default.
 *
 * The 'embedding' field in EmbeddingRow is typed as unknown because pgvector
 * returns it as a string in the form '[0.1,0.2,...]' — callers that need the
 * raw vector should parse it. In practice, search() does not SELECT the stored
 * embedding, so this is not needed in Phase 1.
 */

// ---------------------------------------------------------------------------
// documents
// ---------------------------------------------------------------------------

export interface DocumentRow {
  id: string;
  status: string;
  filename: string;
  contentType: string;
  fileSizeBytes: string | null; // bigint returns as string from pg driver
  fileHash: string | null;
  storagePath: string | null;
  date: string | null;
  description: string;
  documentType: string | null;
  people: string[] | null;
  organisations: string[] | null;
  landReferences: string[] | null;
  flagReason: string | null;
  flaggedAt: Date | null;
  submitterIdentity: string;
  ingestionRunId: string | null;
  groupName: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export type DocumentInsert = Omit<DocumentRow, 'createdAt' | 'updatedAt'>;

// ---------------------------------------------------------------------------
// chunks
// ---------------------------------------------------------------------------

export interface ChunkRow {
  id: string;
  documentId: string;
  chunkIndex: number;
  text: string;
  tokenCount: number;
  createdAt: Date;
}

export type ChunkInsert = Omit<ChunkRow, 'createdAt'>;

// ---------------------------------------------------------------------------
// embeddings
// ---------------------------------------------------------------------------

export interface EmbeddingRow {
  id: string;
  chunkId: string;
  documentId: string;
  embedding: unknown; // pgvector string representation — not used in selects
}

export type EmbeddingInsert = Omit<EmbeddingRow, 'embedding'> & {
  embedding: number[];
};

// ---------------------------------------------------------------------------
// vocabulary_terms
// ---------------------------------------------------------------------------

export interface VocabularyTermRow {
  id: string;
  term: string;
  normalisedTerm: string;
  category: string;
  description: string | null;
  aliases: string[];
  source: string;
  confidence: number | null;
  createdAt: Date;
  updatedAt: Date;
}

export type VocabularyTermInsert = Omit<
  VocabularyTermRow,
  'createdAt' | 'updatedAt'
>;

// ---------------------------------------------------------------------------
// vocabulary_relationships
// ---------------------------------------------------------------------------

export interface VocabularyRelationshipRow {
  id: string;
  sourceTermId: string;
  targetTermId: string;
  relationshipType: string;
  confidence: number | null;
}

export type VocabularyRelationshipInsert = VocabularyRelationshipRow;

// ---------------------------------------------------------------------------
// rejected_terms
// ---------------------------------------------------------------------------

export interface RejectedTermRow {
  id: string;
  normalisedTerm: string;
  originalTerm: string;
  rejectedAt: Date;
}

export type RejectedTermInsert = Omit<RejectedTermRow, 'rejectedAt'>;

// ---------------------------------------------------------------------------
// entity_document_occurrences
// ---------------------------------------------------------------------------

export interface EntityDocumentOccurrenceRow {
  id: string;
  termId: string;
  documentId: string;
  createdAt: Date;
}

export type EntityDocumentOccurrenceInsert = Omit<
  EntityDocumentOccurrenceRow,
  'createdAt'
>;

// ---------------------------------------------------------------------------
// processing_runs
// ---------------------------------------------------------------------------

export interface ProcessingRunRow {
  id: string;
  status: string;
  documentsQueued: number;
  createdAt: Date;
  completedAt: Date | null;
}

export type ProcessingRunInsert = Omit<ProcessingRunRow, 'createdAt'>;

// ---------------------------------------------------------------------------
// pipeline_steps
// ---------------------------------------------------------------------------

export interface PipelineStepRow {
  id: string;
  documentId: string;
  stepName: string;
  status: string;
  attemptCount: number;
  errorMessage: string | null;
  startedAt: Date | null;
  completedAt: Date | null;
  createdAt: Date;
}

export type PipelineStepInsert = Omit<PipelineStepRow, 'createdAt'>;

// ---------------------------------------------------------------------------
// ingestion_runs
// ---------------------------------------------------------------------------

export interface IngestionRunRow {
  id: string;
  status: string;
  sourceDirectory: string;
  grouped: boolean;
  createdAt: Date;
  completedAt: Date | null;
}

export type IngestionRunInsert = Omit<IngestionRunRow, 'createdAt'>;
